### ISSUE TITLE
Failed to run FastRCNN (no change in any code from git) in "evaluate" mode

### ISSUE THREAD

**Issue by jwook1004** [tensorpack/tensorpack#919] opened 2018-10-04 15:55 UTC
Thanks for the great work.

I failed to run FastRCNN in "evaluate" mode, getting various errors (segmentaion fault, invalid argument, abort, etc.). The seeting seems to be similar to the [previous issue](https://github.com/tensorpack/tensorpack/issues/861), but different with the following details:
1) I use 8 V100s with "replicated" trainer
2) I run with "-evaluate" option to run only evaluation
3) No change made in any code. (code from commit=81a4fc332eeae7e230e0736958014a0958fca822) In particular, I used "replicated" trainer as the default setting.

1. What you did:
  + If you're using examples:
    + What's the command you run:
> python3 train.py --evaluate output.json --load /nvme0/choij/Workspace/tensorpack_sentient/examples/FasterRCNN/models/COCO-R50C4-MaskRCNN-Standard.npz

    + Have you made any changes to code? Paste them if any:
> No. The code is cloned on Oct 4 (commit=81a4fc332eeae7e230e0736958014a0958fca822)

  + If not, tell us what you did that may be relevant.
    But we may not investigate it if there is no reproducible code.
> I downloaded `COCO-R50C4-MaskRCNN-Standard.npz` from the model zoo.

  + Better to paste what you did instead of describing them.

2. What you observed, including but not limited to the __entire__ logs.
  + Better to paste what you observed instead of describing them.
    + As can be shown below, different error messages come up for different runs. 
    + Error message example 1) Segmentation fault
![image](https://user-images.githubusercontent.com/39837223/46484320-89da3b00-c7c7-11e8-827b-076080b58591.png)
    + Error message example 2) Invalid argument
![image](https://user-images.githubusercontent.com/39837223/46485750-53ea8600-c7ca-11e8-8be7-e8aca02cc1a8.png)
![image](https://user-images.githubusercontent.com/39837223/46485761-5a78fd80-c7ca-11e8-8d43-109d0f28f9c1.png)
    + Error message example 3) Abort with "tensorflow/core/common_runtime/bfc_allocator.cc:462] Check failed: c->in_use() && (c->bin_num == kInvalidBinNum)
![image](https://user-images.githubusercontent.com/39837223/46486073-fd317c00-c7ca-11e8-9a6b-f42290a00f07.png)
    + FYI: I use the following setting:
![image](https://user-images.githubusercontent.com/39837223/46486433-c0b25000-c7cb-11e8-9580-7076bccf20e7.png)
![image](https://user-images.githubusercontent.com/39837223/46486439-c5770400-c7cb-11e8-83f7-7aa22b50a352.png)

3. What you expected, if not obvious.
> I expected that there's some issue with "evaluate" code with multi-gpu setting.

4. Your environment:
  + Python version.
  + TF version: `python -c 'import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)'`.
> v1.11.0-0-gc19e29306c 1.11.0
  + Tensorpack version: `python -c 'import tensorpack; print(tensorpack.__version__)'`.
      You can install Tensorpack master by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`.:
> 0.8.9
  + Hardware information, e.g. number of GPUs used.
>  Tesla V100, 8 GPUs

About efficiency issues, PLEASE first read http://tensorpack.readthedocs.io/en/latest/tutorial/performance-tuning.html

**Comment by ppwwyyxx** [comment] 2018-10-04 16:18
I can reproduce the issue, however the same thing works for TF 1.10.
This could be a bug in tensorflow and I'll investigate. For the moment please use 1.10 instead.

**Comment by jwook1004** [comment] 2018-10-04 18:52
Confirmed that TF 1.10 works without the problems reported here. Closing the issue.

**Comment by ppwwyyxx** [comment] 2018-10-05 22:04
Closing since it's a TF bug. Tracking https://github.com/tensorflow/tensorflow/issues/22750 instead.

**Closed by ppwwyyxx** 2018-10-05 22:04 UTC
Labels: upstream bug
