### ISSUE TITLE
Is it possible to use QueueInput/InputSource as input to my self-defined graph?

### ISSUE THREAD

**Issue by DreamChaserMXF** [tensorpack/tensorpack#1030] opened 2019-01-04 13:53 UTC
Hi,
I was using my own training framework (based on tensorflow's low level API) to reproduce ResNet-50. However, I found out that it's hard to reach the accuracy claimed in the [paper](https://arxiv.org/abs/1512.03385) as well as [tensorpack's ResNet demo](https://github.com/tensorpack/tensorpack/tree/master/examples/ResNet). I tried to substitude tensorpack's ResNet layers for my own ones, it turned out the training speed was improved, but the Top-1 accuracy (single crop) was never beyond 67%. There must be something wrong!!! I was wondering if QueueInput in tensorpack's ResNet demo could be used as my graph's input, so that I can confirm whether the problem is the correctness of my data source, or some tricks among data augmentation.

I read the tensorpack's source code, but still confused about the usage of callback functions returned by QueueInput.setup(). Is it possible to use InputSource/QueueInput as input in my self-defined graph?

**Comment by ppwwyyxx** [comment] 2019-01-04 17:58
Duplicate of #783 . No, it's not possible.

**Closed by ppwwyyxx** 2019-01-04 17:58 UTC
