### ISSUE TITLE
why the map is so low. this is trained on coco dataset! and when i run the predict ,but i got nothing instance ,is there anything wrong?

### ISSUE THREAD

**Issue by horizonheart** [tensorpack/tensorpack#953] opened 2018-10-29 07:24 UTC
![image](https://user-images.githubusercontent.com/16372054/47635070-a54e2100-db8e-11e8-831f-22b99f724584.png)
i change the predict as follows,but the result is same as the original picture
![image](https://user-images.githubusercontent.com/16372054/47639058-55c22200-db9b-11e8-94b7-72ceab490757.png)
i print the detect result and found the result is [].I have tried many pictures.I am very confused!

![image](https://user-images.githubusercontent.com/16372054/47643016-2a443500-dba5-11e8-991e-7e450a7a9657.png)
![image](https://user-images.githubusercontent.com/16372054/47643389-53b19080-dba6-11e8-8446-7a209744d5ce.png)

**Comment by ppwwyyxx** [comment] 2018-10-29 12:31
For anyone to better diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

**Comment by horizonheart** [comment] 2018-10-29 12:40
> For anyone to better diagnose your issue, please post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md))

i used four gpu to train and used one gpu to inference!

**Comment by ppwwyyxx** [comment] 2018-10-29 14:29
Please post relevant details following the issue template in the link above. In particular, I do not understand what you did, what you observed and what you expected.

**Comment by horizonheart** [comment] 2018-10-29 14:46
> Please post relevant details following the issue template in the link above. In particular, I do not understand what you did, what you observed and what you expected.

i used the tensorpack to train coco dataset and used the default configuration. i can train the model success. But when i predict the model , but the predict image is the same as original image,in other wors, the model don't find any box and segmentation.

**Comment by ppwwyyxx** [comment] 2018-10-29 15:53
Please post the details following the issue template in the link above, i.e.:

1. What you did:
  + If you're using examples:
    + What's the command you run:
    + Have you made any changes to the examples? Paste them if any:
  + If not, tell us what you did that may be relevant.
    But we may not investigate it if there is no reproducible code.
  + Better to paste what you did instead of describing them.
2. What you observed, including but not limited to the __entire__ logs.
  + Better to paste what you observed instead of describing them.
3. What you expected, if not obvious.

Since you mentioned both training and prediction, I assume that's two separate commands. Therefore please post two group of relevant information (what you did and what you observed) for the two commands, respectively.

**Comment by horizonheart** [comment] 2018-10-30 01:47
> Please post the details following the issue template in the link above, i.e.:
> 
> 1. What you did:
> 
> * If you're using examples:
>   
>   * What's the command you run:
>   * Have you made any changes to the examples? Paste them if any:
> * If not, tell us what you did that may be relevant.
>   But we may not investigate it if there is no reproducible code.
> * Better to paste what you did instead of describing them.
> 
> 1. What you observed, including but not limited to the **entire** logs.
> 
> * Better to paste what you observed instead of describing them.
> 
> 1. What you expected, if not obvious.
> 
> Since you mentioned both training and prediction, I assume that's two separate commands. Therefore please post two group of relevant information (what you did and what you observed) for the two commands, respectively.

ok,thanks! i have pasted the question https://github.com/tensorpack/tensorpack/issues/955

**Comment by ppwwyyxx** [comment] 2018-10-30 01:50
Closing this due to #955.

**Closed by ppwwyyxx** 2018-10-30 01:50 UTC
