### ISSUE TITLE
CUDA ERROR Illegal adress

### ISSUE THREAD

**Issue by MikeyLev** [tensorpack/tensorpack#1173] opened 2019-05-01 04:18 UTC
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:
I Ran the fasterRCNN example on my dataset all is working fine until some cuda error happened. on epoch 37
(1) **If you're using examples, what's the command you run:**
puthon3 train.py

(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**
No
(3) **If not using examples, tell us what you did:**

  It's always better to copy-paste what you did than to describe them.

  Please try to provide enough information to let other __reproduce__ your issues. 
  Without reproducing the issue, we may not be able to investigate it.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**

It's always better to copy-paste what you observed instead of describing them.

It's always better to paste **as much as possible**, although sometimes a partial log is OK.
[0430 17:54:46 @base.py:275] Start Epoch 10 ...
 37%|############################################################5                                                                                                        |2529/6894[09:32<16:29, 4.41it/s]2019-04-30 18:04:19.943985: E tensorflow/stream_executor/cuda/cuda_event.cc:48] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-04-30 18:04:19.943985: E tensorflow/stream_executor/cuda/cuda_event.cc:48] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
2019-04-30 18:04:19.944066: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:274] Unexpected Event status: 1
2019-04-30 18:04:19.944077: F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:274] Unexpected Event status: 1

Tensorpack typically saves stdout to its training log.
If stderr is relevant, you can run a command with `CMD 2>&1 | tee logs.txt`
to save both stdout and stderr to one file.

(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.

### 3. What you expected, if not obvious.

If you expect higher speed, please read
http://tensorpack.readthedocs.io/tutorial/performance-tuning.html 
before posting.

If you expect certain accuracy, only in one of the two conditions can we help with it:
(1) You're unable to reproduce the accuracy documented in tensorpack examples.
(2) It appears to be a tensorpack bug.

Otherwise, how to train a model to certain accuracy is a machine learning question.
We do not answer machine learning questions and it is your responsibility to 
figure out how to make your models more accurate.

### 4. Your environment:
  + Paste the output of this command: `python3 -c 'import tensorpack.tfutils as u; print(u.collect_env_info())'`
    If this command failed, tell us your version of Python/TF/tensorpack.
  + You can install Tensorpack master by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`
    and see if your issue is already solved.
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell. 
  + Include relevant hardware information, e.g. number of GPUs used for training, amount of RAM.

You may often want to provide extra information related to your issue, but
at the minimum please try to provide the above information __accurately__ to save effort in the investigation.

**Comment by ppwwyyxx** [comment] 2019-05-03 17:21
CUDA error is most likely either a nvidia bug or a tensorflow bug. 
We cannot reproduce this issue to help you.

**Comment by ppwwyyxx** [comment] 2019-05-03 17:58
Your best shot is to upgrade nvidia driver/cuda/cudnn or upgrade/downgrade tensorflow. You can search your error message in `tensorflow/issues` for related ones.
Closing as I believe this issue is not related to tensorpack.

**Closed by ppwwyyxx** 2019-05-03 17:58 UTC
Labels: upstream issue
