### ISSUE TITLE
Tensorpack crashes upon evaluation

### ISSUE THREAD

**Issue by zvikapeter** [tensorpack/tensorpack#959] opened 2018-10-31 08:53 UTC
Hello,

When training FasterRCNN on COCO2014 - Tensorpack crashes for me upon evaluation with the following error:
1031 10:42:17 @train.py:484] Running evaluation ...
Backend TkAgg is interactive backend. Turning interactive mode on.
  0%|          | 172/40504 [00:36<1:28:26,  7.60it/s]2018-10-31 10:46:31.508464: F tensorflow/core/common_runtime/bfc_allocator.cc:462] Check failed: c->in_use() && (c->bin_num == kInvalidBinNum) 

Im running on GTX1080, under ubuntu16, python 3.6.
I added in the config file:
os.environ['TF_CUDNN_USE_AUTOTUNE'] = '0'
and it didnt work.

also changed EVAL_PERIOD to 1 , STEPS_PER_EPOCH to 1, BATCH_PER_IM to 32 - just for sanity check and memory issues

Anyone has any idea?

Thanks...

**Comment by ppwwyyxx** [comment] 2018-10-31 08:59
For anyone to better diagnose your issue, please always post relevant details following the issue template (click "New Issue" -> "Unexpected Problems / Bugs", or visit [this link to post issues about unexpected problems](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md)).

Your issue is a duplicate of #919.

**Closed** 2018-10-31 08:59 UTC
Labels: duplicate, upstream bug

**Comment by zvikapeter** [comment] 2018-10-31 13:55
Thanks. Downgrading TensorFlow to 1.10 solved the issue.
