### ISSUE TITLE
'ResNetC4Model' attribute error

### ISSUE THREAD

**Issue by yasserkhalil93** [tensorpack/tensorpack#960] opened 2018-10-31 16:58 UTC
I am getting the following error:

**AttributeError: 'ResNetC4Model' object has no attribute 'input_names'**

When trying to train using the following command:

**./train.py --config MODE_MASK=False MODE_FPN=False DATA.BASEDIR=/media/ext-drive/datasets/coco/coco BACKBONE.WEIGHTS=/media/ext-drive/faster_rcnn/faster_rcnn_new/tensorpack-master/examples/FasterRCNN/models/ImageNet-R50-AlignPadding.npz**

Does anyone knows what is the problem?
PS: I have tensorflow version 1.4.1

**Comment by ppwwyyxx** [comment] 2018-10-31 17:54
A duplicate of #875

**Comment by ppwwyyxx** [comment] 2018-10-31 18:03
tensorpack 0.9 was just pushed to pypi: https://pypi.org/project/tensorpack/
Reinstall from pypi or github master should solve the issue.

**Closed by ppwwyyxx** 2018-10-31 18:03 UTC
Labels: duplicate

**Comment by ppwwyyxx** [comment] 2018-11-01 04:33
That means you're still using the old tensorpack.
The command to install latest tensorpack is in the [README](https://github.com/tensorpack/tensorpack/) as well as the [issue template](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md):
`pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`
The command to see current tensorpack version is also in the [issue template](https://github.com/tensorpack/tensorpack/issues/new?template=unexpected-problems---bugs.md):
`python -c 'import tensorpack; print(tensorpack.__version__)'`.

**Comment by yasserkhalil93** [comment] 2018-11-01 07:55
Thank you very much. Using `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git` solved the issue.

However, now I am facing another error.
**tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[512,1024,14,14]**

Eventhough I pulled down the **_C.RPN.TEST_POST_NMS_TOPK** parameter from 1000 to 100 but still I am getting the same error.

The GPU I am using is Geforce GTX1080 with 8GB.

**Comment by ppwwyyxx** [comment] 2018-11-01 07:58
Your GPU does not have enough memory to run it. You'll need to change your models.

**Comment by ppwwyyxx** [comment] 2018-11-01 08:09
The FasterRCNN example does not include small models. For large models you can also try: 1. use FPN and 2. use a smaller `FRCNN.BATCH_PER_IM`.

**Comment by yasserkhalil93** [comment] 2018-11-01 08:37
I reduced the parameter `FRCNN.BATCH_PER_IM` to 128 but still is giving me the same error.

I want to train COCO on FasterRCNN. Hence, I need a model pretrained on Imagenet. 
So, you are suggesting it is impossible to train such case on my GPU.

Regards.

**Comment by ppwwyyxx** [comment] 2018-11-01 08:57
I think 8G is probably enough if you use FPN and a small BATCH_PER_IM

**Comment by yasserkhalil93** [comment] 2018-11-01 09:05
What do you mean by FPN? Setting the parameter to true in the following command:

**./train.py --config MODE_MASK=False MODE_FPN=False DATA.BASEDIR=/media/ext-drive/datasets/coco/coco BACKBONE.WEIGHTS=/media/ext-drive/faster_rcnn/faster_rcnn_new/tensorpack-master/examples/FasterRCNN/models/ImageNet-R50-AlignPadding.npz**

Thanks

**Comment by ppwwyyxx** [comment] 2018-11-01 09:09
MODE_FPN=True
