### ISSUE TITLE
Exporting to a frozen and pruned graph for inference produces invalid graph

### ISSUE THREAD

**Issue by technicaldebt7** [tensorpack/tensorpack#1064] opened 2019-01-28 21:43 UTC
### 1. What you did:

(1) **If you're using examples, what's the command you run:**

For context, I trained a ResNetFPNModel and am attempting to export the graph properly as a .pb file. I am able to export the graph to a .pb file, but am not able to import that graph later for inference. I referenced https://tensorpack.readthedocs.io/tutorial/inference.html to create the code below:

    from tensorpack.tfutils.export import ModelExporter
    from train import ResNetFPNModel

    MODEL = ResNetFPNModel()
    pred_config = PredictConfig(
                    model=MODEL,
                    session_init=get_model_loader(".../model-480000"),
                    input_names=MODEL.get_inference_tensor_names()[0],
                    output_names=['tower-pred-0/output/boxes', 'tower-pred-0/output/scores', 'tower-pred-0/output/labels'])

    ModelExporter(pred_config).export_compact('.../compact_graph.pb')
    
    pbfile = ".../compact_graph.pb"
    with tf.gfile.FastGFile(pb_file, 'rb') as f:
           graph_def = tf.GraphDef()
           graph_def.ParseFromString(f.read())

    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    self.sess = tf.Session(config=config)
    self.sess.graph.as_default()
    tf.import_graph_def(graph_def, name='')

The last line of code in the above code segment throws the error.

(2) **If you're using examples, have you made any changes to the examples? Paste `git diff` here:**

I included the 'git diff' in the attached 'git_diff.txt' file as pasting directly into here was poorly formatted
[git_diff.txt](https://github.com/tensorpack/tensorpack/files/2805086/git_diff.txt)

### 2. What you observed:

(1) **Include the ENTIRE logs here:**

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 418, in import_graph_def
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: tower-pred-0/output/map/while/add/y = Const[dtype=DT_INT32, value=Tensor<type: int32 shape: [] values: 1>](tower-pred-0/output/map/while/Switch:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dl_docker_burrojo/gatr_python/sandbox_burrows.py", line 869, in <module>
    fast_model_evaluator()
  File "/home/dl_docker_burrojo/gatr_python/sandbox_burrows.py", line 834, in fast_model_evaluator
    nms_threshold=0.2)
  File "/home/dl_docker_burrojo/gatr_python/sandbox_burrows.py", line 604, in __init__
    tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 454, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 422, in import_graph_def
    raise ValueError(str(e))
ValueError: NodeDef expected inputs '' do not match 1 inputs specified; Op<name=Const; signature= -> output:dtype; attr=value:tensor; attr=dtype:type>; NodeDef: tower-pred-0/output/map/while/add/y = Const[dtype=DT_INT32, value=Tensor<type: int32 shape: [] values: 1>](tower-pred-0/output/map/while/Switch:1)

(2) **Other observations, if any:**
I was able to create a frozen graph from the meta graph and weights (outputted to the train_log) using the code below:

    import tensorflow as tf
    from tensorflow.python.framework import graph_util

    # We retrieve our checkpoint fullpath
    checkpoint = tf.train.get_checkpoint_state(model_folder)
    input_checkpoint = checkpoint.model_checkpoint_path
    output_node_names = ['tower-pred-0/output/boxes', 'tower-pred-0/output/scores', 'tower-pred-0/output/labels']

    # We clear devices to allow TensorFlow to control on which device it will load operations
    clear_devices = True

    # We import the meta graph and retrieve a Saver
    saver = tf.train.import_meta_graph('.../graph-0117-231734.meta', clear_devices=clear_devices)

    # We retrieve the protobuf graph definition
    graph = tf.get_default_graph()
    input_graph_def = graph.as_graph_def()

    # We start a session and restore the graph weights
    with tf.Session() as sess:
        saver.restore(sess, input_checkpoint)

        # We use a built-in TF helper to export variables to constants
        output_graph_def = graph_util.convert_variables_to_constants(
            sess,  # The session is used to retrieve the weights
            input_graph_def,  # The graph_def is used to retrieve the nodes
            output_node_names  # The output node names are used to select the usefull nodes
        )
       
        graph_io.write_graph(output_graph_def, ".", output_graph, as_text=False)

I am able to import the frozen graph produced from the code above without error, and do inference. However when I optimize that frozen graph using the optimize_for_inference function in tensorflow.python.tools.optimize_for_inference_lib, I get the same error as above when attempting to import the optimized graph.

### 3. What you expected, if not obvious.

I expected to be able to import the Tensorflow Graph created by ModelExporter's export_compact function i.e. ( tf.import_graph_def(graph_def, name='') ) to be used later for inference.  However importing the graph throws the above errors.  

### 4. Your environment:
  + Python version: Python 3.5.2
  + TF version: v1.10.1-0-g4dcfddc5d1 1.10.1
  + Tensorpack version: 0.9.0.1
  + GPU: One Quadro P4000 @ 1.48 GHz

**Comment by ppwwyyxx** [comment] 2019-01-28 22:46
Thanks for the details!
I can reproduce your issue, and removing the `optimize_for_inference` function call at  https://github.com/tensorpack/tensorpack/blob/21c494697faa40db0e280a3c53abad2521b2e1f6/tensorpack/tfutils/export.py#L74-L79 makes it work, which agrees with your findings.
So it appears to be a bug in tensorflow. It optimizes a good graph to something wrong.

**Comment by technicaldebt7** [comment] 2019-01-28 22:59
Thanks for the reply!
Do you have any recommendations for other ways of optimizing the frozen graph?

**Comment by ppwwyyxx** [comment] 2019-01-28 23:04
I do not have other recommendations except to manually write a faster graph (which I sometimes do). Inference is not the focus of this project, so we only do what tensorflow can do in this project.

**Comment by ppwwyyxx** [comment] 2019-01-29 00:20
For the record, this was the code I used in `train.py` to reproduce the issue:
```python
    from tensorpack.tfutils.export import ModelExporter
    finalize_configs(is_training=False)
    pred_config = PredictConfig(
                model=MODEL,
                session_init=get_model_loader("/home/yuxinwu/data/models/FasterRCNN/COCO-R50FPN-MaskRCNN-Standard.npz"),
                input_names=MODEL.get_inference_tensor_names()[0],
                output_names=['output/boxes', 'output/scores', 'output/labels'])
 
    pbfile = "./compact_graph.pb"
    ModelExporter(pred_config).export_compact(pbfile, optimize=False)
 
    with tf.gfile.FastGFile(pbfile, 'rb') as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
 
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    sess = tf.Session(config=config)
    sess.graph.as_default()
    with tf.Graph().as_default():
        tf.import_graph_def(graph_def, name='')
    import sys; sys.exit()
```

Closing since it's a tensorflow issue. Will add an option in exporter to skip `optimize_for_inference` to avoid this.

**Closed by ppwwyyxx** 2019-01-29 00:20 UTC
