### ISSUE TITLE
tensorpack hangs -- potential issue with fork method

### ISSUE THREAD

**Issue by tbenst** [tensorpack/tensorpack#1416] opened 2020-04-01 01:38 UTC
When trying to run the DeepLabCut test script, it hangs when tensorpack is used. imgaug works, however. This appears to occur on all platforms except Ubuntu ([Windows, Mac, & NixOS are known to hang](https://github.com/AlexEMG/DeepLabCut/issues/637#issuecomment-606868137)).

(1) **If you're using examples, what's the command you run:**
python [testscript.py](https://github.com/AlexEMG/DeepLabCut/blob/master/examples/testscript.py)
(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**
No

### 2. What you observed:

(1) **Include the ENTIRE logs here:**
[output](https://gist.github.com/tbenst/db8f258c7f3bdc0f8d1d024342513798)

Possibly relevant warning:
```
[0331 19:38:06 @argtools.py:146] WRN Starting a process with 'fork' method is not safe and may consume unnecessary extra CPU memory. Use 'forkserver/spawn' method (available after Py3.4) instead if you run into any issues. See https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods

```

(2) **Other observations, if any:**
CPU utilization is at zero. Perhaps a thread does not cleanly shutdown?

### 3. What you expected, if not obvious.
Program should not hang. Does not occur with imgaug. Only occurs with tensorpack on non-Ubuntu platforms. Thus, appears to be tensorpack bug.

### 4. Your environment:

Paste the output of this command: `python -c 'import tensorpack.tfutils as u; print(u.collect_env_info())'`
If this command failed, tell us your version of Python/TF/tensorpack.

Tested on `0.10`

Note that all tensorpack tests succeed, as tested with `bash tests/run-tests.sh`.

**Comment by ppwwyyxx** [comment] 2020-04-01 01:47
Most part of your code is unrelated to tensorpack and have a lot of dependencies. So I can't easily run it and even if I can it's not clear that the issue is in tensorpack, rather than some other code or code that uses tensorpack incorrectly.

It would make more sense to create a [MVCE](https://stackoverflow.com/help/minimal-reproducible-example) for anyone to be able to investigate an issue.

**Comment by tbenst** [comment] 2020-04-01 02:14
@AlexEMG @MMathisLab let us know if you're able to provide any more specificity on the hanging issue? Many thanks!

**Comment by MMathisLab** [comment] 2020-04-01 02:50
@tbenst here is the original PR that introduced tensorpack, if helpful to look at the minimal code: https://github.com/AlexEMG/DeepLabCut/pull/409

**Comment by MMathisLab** [comment] 2020-04-01 02:51
and a issue/update were @ppwwyyxx kindly gave great advice: https://github.com/AlexEMG/DeepLabCut/issues/429

**Comment by ppwwyyxx** [comment] 2020-05-22 19:06
Closing as there is no repro.
As the issue already mentioned,  the use of `fork` could cause this and using "spawn" or "forkserver" https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods is more robust.

Related: #1447

**Closed by ppwwyyxx** 2020-05-22 19:06 UTC
