### ISSUE TITLE
dataflow is not working properly after model resore

### ISSUE THREAD

**Issue by mikeun** [tensorpack/tensorpack#803] opened 2018-06-26 06:25 UTC
Usage Questions:
I use two pretrained models (PM) to restore weights. After that I train some new variables (added to new model (NM)) with fixed restored weights.
Dataflows are different (different dataset sizes but batch sizes are same) in my NM model vs PM model.
Dataflow of NM is constructed to generate 10240 instances per epoch (self.epoch_size = 10240), batch size is 1024, number of epoch is set to 80. -- VVVVVVVV --
```
    def get_data(self):
        if self.epoch_counter in self.instance_trigger:
            self.instance_index = self.instance_trigger.index(self.epoch_counter)
            self.instance_value = self.data_arr[self.instance_index]
        if self.epoch_counter in self.label_trigger:
            self.label_index = self.label_trigger.index(self.epoch_counter)
            self.label_value = self.label[self.label_index]
            self.instance_id = self.analyze_id[self.label_index]
        self.datapoint = (self.instance_value, np.array([self.instance_id, self.label_value, 1.]))
        self.epoch_counter += 1
        print(">>>>>>>>>>>>>>>>>>>>>>>>><><><><>< --------------------", self.epoch_counter)
        for i in range(self.epoch_size):
            yield self.datapoint
```

Dataflow of PM is depend on train data size ~ 1'400'000, batch size is 1024, number of epoch 100.

When I started to train NM - epoch size (number of instances) is wrong:
it prints each epoch number I planned like >>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- . 
```
[0626 08:12:18 @base.py:241] Graph Finalized.
[0626 08:12:18 @concurrency.py:37] Starting EnqueueThread BatchQueueInput/input_queue ...
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 1
[0626 08:12:18 @steps.py:126] Start training with global_step=1652310
[0626 08:12:19 @param.py:148] [HyperParamSetter] At global_step=1652310, optimizer/learning_rate will change to 0.00100000
[0626 08:12:19 @base.py:261] Start Epoch 1 ...
  0%|                                                                                                                                                                                          |0/10[00:00<?,?it/s]>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 2
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 3
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 4
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 5
 10%|#################8                                                                                                                                                                |1/10[00:44<06:42, 0.02it/s]>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 6
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 7
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 8
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 9
 20%|###################################6                                                                                                                                              |2/10[00:52<03:28, 0.04it/s]>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 10
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 11
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 12
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 13
 30%|#####################################################4                                                                                                                            |3/10[00:59<01:57, 0.06it/s]>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 14
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 15
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 16
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 17
 40%|#######################################################################2                                                                                                          |4/10[01:07<01:12, 0.08it/s]>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 18
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 19
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 20
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 21
 50%|#########################################################################################                                                                                         |5/10[01:14<00:49, 0.10it/s]>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 22
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 23
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 24
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 25
 60%|##########################################################################################################8                                                                       |6/10[01:22<00:34, 0.12it/s]>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 26
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 27
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 28
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 29
 70%|############################################################################################################################6                                                     |7/10[01:29<00:24, 0.12it/s]>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 30
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 31
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 32
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 33
 80%|##############################################################################################################################################4                                   |8/10[01:37<00:15, 0.13it/s]>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 34
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 35
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 36
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 37
 90%|################################################################################################################################################################2                 |9/10[01:44<00:07, 0.13it/s]>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 38
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 39
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 40
>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- 41
100%|#################################################################################################################################################################################|10/10[02:31<00:00, 0.04it/s]
[0626 08:14:51 @base.py:271] Epoch 1 (global_step 1652711) finished, time:2 minutes 31 seconds.
[0626 08:14:51 @saver.py:84] Model saved to ./data/train_dir/eone_max1000626-081148/model-1652711.
[0626 08:14:52 @monitor.py:433] BatchQueueInput/queue_size: 201.46
[0626 08:14:52 @monitor.py:433] EstimatePDF/Neg: 9.4756e+07
[0626 08:14:52 @monitor.py:433] conf matrix of class 0: |         0|         0|, Recall:-1.00, Precision: -1
[0626 08:14:52 @monitor.py:433] conf matrix of class 1: |         0|    410624|, Recall:100.00, Precision: 100
[0626 08:14:52 @monitor.py:433] loss/accuracy: 1
[0626 08:14:52 @monitor.py:433] loss/cross_entropy_loss: 1.318e-11
[0626 08:14:52 @monitor.py:433] loss/train_error: 3.3758e-10
[0626 08:14:52 @monitor.py:433] optimizer/learning_rate_1: 0.001

```
epoch size is 410624 instances - why? one epoch includes 40 of epochs I planned?

```
        dataset_train, _, max_epoch = get_data()  # dataset_train is Dataflow, max_epoch = 80
        dataset_train = BatchQueueInput(dataset_train, 1024)
        steps_per_epoch = dataset_train.size()  # steps_per_epoch = 10 (10240 / 1024)

        output_config = {
                'steps_per_epoch': steps_per_epoch,
                'callbacks': [
                    ConfusionMatrixAfterEpoch('prediction/predicted_class', 'InputBlock/label/label', label_list)
                ],
                'max_epoch': max_epoch,
                "session_init": ChainInit(
                    [
                        SaverRestoreRelaxed(pdf_model),
                        SaverRestoreRelaxed(fm_model)
                    ]
                )
        }

```

4. Your environment:
	+ Python version: Python 3.6.2 |Intel Corporation| (default, Aug 15 2017, 16:14:26)
	+ TF version: b'v1.8.0-3413-g8e86dcd1c5' 1.9.0-rc0.
	+ Tensorpack version: 0.8.5

**Comment by ppwwyyxx** [comment] 2018-06-26 06:38
I can't understand what is your question. Could you simplify and clarify?
It seems that the number "410624" in the log is not what you expected, but I have no idea what code prints that number or how is that related to tensorpack or dataflow.

It seems that the part of logs that contain ">>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- ." is also different from what you expected but I have no idea what you're expecting.

**Comment by mikeun** [comment] 2018-06-26 06:52
I print ```>>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- epoch_N ```
in get_data() of Dataflow each time it should start new epoch.
Settings are:
epoch size is 10240
batch size is 1024
so I epoch is 10 batches by 1024 instances.
but I have got epoch  = 410624 instances = 401 times by 1024 instances (1024 batch size)

**Comment by mikeun** [comment] 2018-06-26 07:00
BatchQueueInput should make batches by 1024 instances 10 times per epoch only - but result is 401 times per epoch.

**Comment by ppwwyyxx** [comment] 2018-06-26 07:57
I still don't fully understand what is the issue. Now my understanding is:
1. Sounds like it has nothing to do with model restore, is that correct? 
2. You're saying that `BatchQueueInput` should give you 1024 instances per step and 10 steps per epoch -- this I agree. But how do you know it did not do so? What code prints the number 410624 and how does this number relate to what `BatchQueueInput` has done?

**Comment by mikeun** [comment] 2018-06-26 08:22
my Dataflow generate 10240 datapoints in "for" cycle - it should be epoch.
it prints ">>>>>>>>>>>>>>>>>>>>>>>>><><><><>< -------------------- epoch_counter" before this "for" cycle. So I see this print each time it should start _new_ epoch and generate 10240 dataponts.
But I see this print many (41) times _inside_ one epoch. 
410624 - this is from confusion matrix - it collects all instances of current epoch (each step generates batch_size of results - this callback collects them after each step and print confusion matrix after epoch for all results in current epoch) and shows them in a table - so sum of them equals number of all instances.
Where is place to stop batches and finish an epoch??

**Comment by mikeun** [comment] 2018-06-26 08:39
All this about to change datapoints values of different epochs. I feed different values in different epochs.

**Comment by ppwwyyxx** [comment] 2018-06-26 08:44
1. What callbacks do you use for training? 
2. Did you write any callbacks that contains things like `sess.run` or `tensor.eval()`? If yes, what do they look like?

**Comment by mikeun** [comment] 2018-06-26 08:50
```
                'callbacks': [
                    ConfusionMatrixAfterEpoch('prediction/predicted_class', 'InputBlock/label/label', label_list),
                    ModelSaver(max_to_keep=3, keep_checkpoint_every_n_hours=6),
                    AnalyzeTensors(
                        save_tensors=['^InputBlock/email_features$'],  # ['^InputBlock/analyze/mix_tensor'],
                        save_ids=['^InputBlock/label/customer$'],  # ['^InputBlock/analyze/mix_tensor'],
                        save_prob=['^prediction/predicted_prob$'],  # ['^InputBlock/analyze/mix_tensor'],
                        init_variables=['analyze'],
                        features_names=get_features(select='email_history')
                    ),
                    ScheduledHyperParamSetter(
                        'optimizer/learning_rate',
                        [
                            (a.analyze['drop0'], a.analyze['lr0'])
                        ]
                    )
                ]

```


```
class AfterTrainEpoch(Callback):

    def _setup_graph(self):
        self.train_tower = self.trainer.tower_func.towers[0]
        self.outputs = [self.train_tower.get_tensor(name) for name in self.get_fetches()]

    def _before_train(self):
        pass

    def _before_epoch(self):
        self._before_train_epoch()

    def _before_train_epoch(self):
        pass

    def _before_run(self, _):
        return tf.train.SessionRunArgs(fetches=self.outputs)

    def _after_run(self, _, run_values):
        self.on_fetches(run_values.results)

    def on_fetches(self, outputs):
        self._on_fetches(outputs)

    def _on_fetches(self, outputs):
        raise NotImplementedError()

    def _trigger_epoch(self):
        ret = self._after_train_epoch()
        if ret is None:
            return
        for k, v in six.iteritems(ret):
            try:
                v = float(v)
            except ValueError:
                logger.warn("{} returns a non-scalar statistics!".format(type(self).__name__))
                continue
            else:
                self.trainer.monitors.put_scalar(k, v)

    def _after_train_epoch(self):
        pass

    def get_fetches(self):
        try:
            ret = self._get_fetches()
        except NotImplementedError:
            logger.warn("Inferencer._get_output_tensors was deprecated and renamed to _get_fetches")
            ret = self._get_output_tensors()

        return [get_op_tensor_name(n)[1] for n in ret]

    def _get_fetches(self):
        raise NotImplementedError()

    def _get_output_tensors(self):
        pass
```


```
class AnalyzeTensors(AfterTrainEpoch):
    """
    Save calculated tensors and initialize feature variables
    """

    def __init__(self,
                 save_tensors: list,
                 save_ids: list,
                 save_prob: list,
                 init_variables: list,
                 features_names: list
                 ):
        """
        Args:
            save_tensors(str): pattern of name tensor to save into file.
            init_variables(str): pattern of tensors to init.
        """
        super().__init__()
        self.save_ids = save_ids
        self.save_prob = save_prob
        self.save_tensors = save_tensors
        self.init_variables = init_variables
        self.features_names = features_names
        self.tensor_values_output_list = list()
        self.prob_output_list = list()
        self.tensor_values_output = None
        self.save_tensors_list = None

    def _setup_graph(self):
        G = tf.get_default_graph()
        self.save_tensors_list = list()
        patterns_list = list()
        patterns_list.extend(self.save_tensors)
        patterns_list.extend(self.save_ids)
        patterns_list.extend(self.save_prob)

        for pattern in patterns_list:
            self.save_tensors_list.extend([
                x.name for x in G.get_operations() if re.search(pattern, x.name)
            ])

        self.ids_output_list = list()

        init_variables_list = list()
        for pattern in self.init_variables:
            init_variables_list.extend([
                x for x in tf.trainable_variables() if re.search(pattern, x.name)
            ])
        self.init_op = tf.variables_initializer(init_variables_list, name='init_analyze_vars')

        super()._setup_graph()

    def _get_fetches(self):
        return self.save_tensors_list

    def _on_fetches(self, outputs):
        self.tensor_values_output, self.ids_output, self.prob_output = outputs

    def _trigger_epoch(self):
        self.tensor_values_output_list.append(self.tensor_values_output)
        self.ids_output_list.append(self.ids_output)
        self.prob_output_list.append(self.prob_output)
        self.init_op.run()

    def _after_train(self):
        a = GetConfig()
        index_values = np.concatenate(self.ids_output_list, axis=0)
        prob_values = np.concatenate(self.prob_output_list, axis=0)
        prob_values = pd.DataFrame(
            prob_values,
            index=index_values.flatten(),
            columns=["prob_{:0>4d}".format(i) for i in range(a.hm_labels)],
            dtype=np.float32)
        all_values = np.concatenate(tuple(self.tensor_values_output_list), axis=0)
        all_values = pd.DataFrame(all_values, index=index_values.flatten(), columns=self.features_names)
        all_values = pd.concat([all_values, prob_values], axis=1)
        folder_to_save = a.folders['analyze']  #  + "{}/".format(self.analyze_id)
        create_folders([folder_to_save])
        table_file = folder_to_save + a.analyze['prediction_file']
        check_files([table_file])
        with pd.HDFStore(table_file, chunkshape='auto', complevel=9, complib='blosc', mode='w') as store:
            store.append(a.analyze['res_table_name'], all_values)
        print("result is saved to \"{}\"".format(table_file))
```

**Comment by ppwwyyxx** [comment] 2018-06-26 09:06
The callbacks look fine.
You can try this code below, modified from the mnist example. It is based on my understanding of what you're doing, and this code works as I expected:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import argparse
import numpy as np



# Just import everything into current namespace
from tensorpack import *
from tensorpack.tfutils import summary
from tensorpack.dataflow import dataset

IMAGE_SIZE = 28


class Model(ModelDesc):
    def inputs(self):
        """
        Define all the inputs (with type, shape, name) that the graph will need.
        """
        return [tf.placeholder(tf.float32, (None, IMAGE_SIZE, IMAGE_SIZE), 'input'),
                tf.placeholder(tf.int32, (None,), 'label')]

    def build_graph(self, image, label):
        """This function should build the model which takes the input variables
        and return cost at the end"""

        # In tensorflow, inputs to convolution function are assumed to be
        # NHWC. Add a single channel here.
        image = tf.expand_dims(image, 3)

        image = image * 2 - 1   # center the pixels values at zero
        # The context manager `argscope` sets the default option for all the layers under
        # this context. Here we use 32 channel convolution with shape 3x3
        with argscope(Conv2D, kernel_size=3, activation=tf.nn.relu, filters=32):
            logits = (LinearWrap(image)
                      .Conv2D('conv0')
                      .MaxPooling('pool0', 2)
                      .Conv2D('conv1')
                      .Conv2D('conv2')
                      .MaxPooling('pool1', 2)
                      .Conv2D('conv3')
                      .FullyConnected('fc0', 512, activation=tf.nn.relu)
                      .Dropout('dropout', rate=0.5)
                      .FullyConnected('fc1', 10, activation=tf.identity)())

        tf.nn.softmax(logits, name='prob')   # a Bx10 with probabilities

        # a vector of length B with loss of each sample
        cost = tf.nn.sparse_softmax_cross_entropy_with_logits(logits=logits, labels=label)
        cost = tf.reduce_mean(cost, name='cross_entropy_loss')  # the average cross-entropy loss

        return cost

    def optimizer(self):
        return tf.train.AdamOptimizer(0.01)



def get_config():
    def gen():
        cnt = 0
        while True:
            cnt += 1
            print('------------', cnt)
            for k in range(1024):
                yield [np.random.rand(28, 28), 0]
    dataset_train = DataFromGenerator(gen)
    steps_per_epoch = 10
    return TrainConfig(
        model=Model(),
        data=BatchQueueInput(dataset_train, 1024),  # the DataFlow instance for training
        callbacks=[ ],
        steps_per_epoch=steps_per_epoch,
        max_epoch=100,
    )


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--gpu', help='comma separated list of GPU(s) to use.')
    parser.add_argument('--load', help='load model')
    args = parser.parse_args()
    if args.gpu:
        os.environ['CUDA_VISIBLE_DEVICES'] = args.gpu

    # automatically setup the directory train_log/mnist-convnet for logging
    logger.auto_set_dir()

    config = get_config()
    if args.load:
        config.session_init = SaverRestore(args.load)
    # SimpleTrainer is slow, this is just a demo.
    # You can use QueueInputTrainer instead
    launch_train_with_config(config, SimpleTrainer())
```

**Comment by mikeun** [comment] 2018-06-26 11:55
I've got same bad results - 

I didn't use simple trainer. 
I use trainer with many optimizer ops:

```
class AnalyzeTrainer(TowerTrainer):
    def __init__(self, input, model, period_class=1, period_pdf=1, period_ohe_l1=1):
        """
        Args:
            input (InputSource):
            model (AnalyzeModelDesc):
        """
        super(AnalyzeTrainer, self).__init__()
        assert isinstance(model, AnalyzeModelDesc), model
        assert isinstance(model, AnalyzeModelDesc), model
        assert min(period_class, period_pdf, period_ohe_l1) == 1
        self.period_class = period_class
        self.period_pdf = period_pdf
        self.period_ohe_l1 = period_ohe_l1
        self.period_ohe_l2 = period_ohe_l2

        inputs_desc = model.get_inputs_desc()
        # Setup input
        cbs = input.setup(inputs_desc)
        self.register_callback(cbs)

        self.tower_func = TowerFuncWrapper(model.build_graph, inputs_desc)
        with TowerContext('', is_training=True):
            self.tower_func(*input.get_input_tensors())
        opt = model.get_optimizer()

        # Define the training iteration
        with tf.name_scope('optimize'):
                self.train_minimize_class = opt.minimize(
                    model.analyze_class_cost,
                    var_list=model.varlist_analyze,
                    name='minimize_analyze_class_cost'
                )

                self.train_minimize_pdf = opt.minimize(
                    model.analyze_pdf_cost,
                    var_list=model.varlist_analyze,
                    name='minimize_analyze_pdf_cost'
                )

                self.train_minimize_ohe_l1 = list()
                for tensor in model.ohe_cost_l1:
                    self.train_minimize_ohe_l1.append(
                        opt.minimize(
                            tensor,
                            var_list=model.varlist_analyze,
                            name='minimize_ohe_l1/' + get_feature_name(tensor.name)
                        )
                    )

    def run_step(self):
            run_op = list()
            if self.global_step % self.period_class == 0:
                run_op.append(self.train_minimize_class)
            if self.global_step % self.period_pdf == 0:
                run_op.append(self.train_minimize_pdf)
            if self.global_step % self.period_ohe_l1 == 0:
                run_op.extend(self.train_minimize_ohe_l1)

            for op in run_op:
                self.hooked_sess.run(op)

```

**Comment by mikeun** [comment] 2018-06-26 12:23
I've found out that it runs get_data() for each self.hooked_sess.run(op).
How can I made Dataflow to be able to control trigger of new epoch?

**Comment by ppwwyyxx** [comment] 2018-06-26 16:44
This is by design of tensorflow. `sess.run([a, b])` is not equivalent to `sess.run(a); sess.run(b)`. You can run the entire list instead of running them separately.

**Comment by ppwwyyxx** [comment] 2018-07-04 17:31
Closing as things are working as expected and it's a tensorflow design.

**Closed by ppwwyyxx** 2018-07-04 17:31 UTC
