### ISSUE TITLE
ImportError: cannot import name 'tfv1' from 'tensorpack'

### ISSUE THREAD

**Issue by Saraaqzs** [tensorpack/tensorpack#1498] opened 2020-12-02 12:27 UTC
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:

 (1) **If you're using examples, what's the command you run:**
I'm running Faster_RCNN_COCO, `python train.py --config BACKBONE.WEIGHTS=/home/aliqoliz/Faster_RCNN_COCO/ImageNet-R50-AlignPadding.npz DATA.BASEDIR=/home/aliqoliz/Faster_RCNN_COCO/COCO/DIR`**** 
(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**

(3) **If not using examples, help us reproduce your issue:**

  It's always better to copy-paste what you did than to describe them.

  Please try to provide enough information to let others __reproduce__ your issues.
  Without reproducing the issue, we may not be able to investigate it.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**
```
python train.py --config BACKBONE.WEIGHTS=/home/aliqoliz/Faster_RCNN_COCO/ImageNet-R50-AlignPadding.npz DATA.BASEDIR=/home/aliqoliz/Faster_RCNN_COCO/COCO/DIR
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    from modeling.generalized_rcnn import ResNetC4Model, ResNetFPNModel
  File "/home/aliqoliz/tensorpack/examples/FasterRCNN/modeling/generalized_rcnn.py", line 4, in <module>
    from tensorpack import tfv1 as tf
ImportError: cannot import name 'tfv1' from 'tensorpack' (/home/aliqoliz/.local/lib/python3.7/site-packages/tensorpack/__init__.py)

```

It's always better to copy-paste what you observed instead of describing them.

It's always better to paste **as much as possible**, although sometimes a partial log is OK.

Tensorpack typically saves stdout to its training log.
If stderr is relevant, you can run a command with `my_command 2>&1 | tee logs.txt`
to save both stdout and stderr to one file.

(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.

### 3. What you expected, if not obvious.
-
If you expect higher speed, please read
http://tensorpack.readthedocs.io/tutorial/performance-tuning.html
before posting.

If you expect the model to converge / work better, note that we do not help you on how to improve a model.
Only in one of the two conditions can we help with it:
(1) You're unable to reproduce the results documented in tensorpack examples.
(2) It indicates a tensorpack bug.

### 4. Your environment:

Paste the output of this command: `python -m tensorpack.tfutils.collect_env`

`/scratch/software/spack/opt/spack/linux-rhel7-broadwell/gcc-9.3.0/python-3.7.7-tasexxbamzkhgrnsozigmogztmgkl7wq/bin/python: No module named tensorpack.tfutils.collect_env`

If this command failed, also tell us your version of Python/TF/tensorpack.

yes it did:

tensorpack==0.10.1
tensorflow==2.0.0
python==3.7.7

Note that:

  + You can install tensorpack master by `pip install -U git+https://github.com/tensorpack/tensorpack.git`
    and see if your issue is already solved.

I did. It doesn't work.

  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell.
-

You may often want to provide extra information related to your issue, but
at the minimum please try to provide the above information __accurately__ to save effort in the investigation.

This issue is not new I have seen it already in closed ones but the solution you suggested didn't solve my problem.
I have cloned tensorpack and COCO from master branch simultaneously (via `git clone https://github.com/tensorpack/tensorpack.git` from master branch) and besides trying `pip install -U git+https://github.com/tensorpack/tensorpack.git` I tried `python setup.py install --user` from cloned repo. I have the same problem anyway and no idea what's going on!
Thanks!

**Comment by Saraaqzs** [comment] 2020-12-02 12:51
The problem solved with changing `from tensorpack import tfv1 as tf` to `from tensorpack.compat import tfv1` in tensorpack/examples/FasterRCNN/modeling/generalized_rcnn.py

**Comment by ppwwyyxx** [comment] 2020-12-02 19:16
Duplicate of #1497

**Closed by ppwwyyxx** 2020-12-02 19:16 UTC
