### ISSUE TITLE
[FasterRCNN] Can't pickle augmentors with lambda in TrainingDataPreprocessor

### ISSUE THREAD

**Issue by dcyoung** [tensorpack/tensorpack#1195] opened 2019-05-17 22:32 UTC
I am using a modified version of the FRCNN with custom pre-processing code.

Commit 8f10b0f8580293721b07a40e3e9d4c6d82398790 introduced a dedicated class for preprocessing: `TrainingDataPreprocessor`.  While this seems to work fine for basic augmentors, the new code is having trouble pickling when augmentors include lambda functions.  

This works:
```python
def __init__(self, cfg):
    self.cfg = cfg
    self.aug = imgaug.AugmentorList(
        [
            CustomResize(cfg.PREPROC.TRAIN_SHORT_EDGE_SIZE, cfg.PREPROC.MAX_SIZE),
            imgaug.Flip(horiz=True),
        ]
    )
```

This does not:
```python
def __init__(self, cfg):
    self.cfg = cfg
    self.aug = imgaug.AugmentorList(
        [
            CustomResize(cfg.PREPROC.TRAIN_SHORT_EDGE_SIZE, cfg.PREPROC.MAX_SIZE),
            imgaug.Flip(horiz=True),
            imgaug.MapImage(aug_fxn, lambda coords: coords),
        ]
    )
```

It throws an error like so:
```bash
[0517 15:18:19 @base.py:209] Setup callbacks graph ...
Traceback (most recent call last):
  File "./train.py", line 143, in <module>
    launch_train_with_config(traincfg, trainer)
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/site-packages/tensorpack/train/interface.py", line 101, in launch_train_with_config
    extra_callbacks=config.extra_callbacks)
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/site-packages/tensorpack/train/base.py", line 344, in train_with_defaults
    steps_per_epoch, starting_epoch, max_epoch)
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/site-packages/tensorpack/train/base.py", line 314, in train
    self.setup_callbacks(callbacks, monitors)
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/site-packages/tensorpack/train/base.py", line 211, in setup_callbacks
    self._callbacks.setup_graph(weakref.proxy(self))
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 59, in setup_graph
    self._setup_graph()
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/site-packages/tensorpack/callbacks/group.py", line 70, in _setup_graph
    cb.setup_graph(self.trainer)
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 59, in setup_graph
    self._setup_graph()
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/site-packages/tensorpack/callbacks/base.py", line 315, in _setup_graph
    self._cb_setup_graph(self)
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/site-packages/tensorpack/input_source/input_source.py", line 38, in <lambda>
    return CallbackFactory(setup_graph=lambda _: df.reset_state())
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/site-packages/tensorpack/dataflow/base.py", line 180, in reset_state
    self.ds.reset_state()
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/site-packages/tensorpack/dataflow/parallel_map.py", line 300, in reset_state
    self._start_processes()
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/site-packages/tensorpack/dataflow/parallel.py", line 104, in _start_processes
    start_proc_mask_signal(self._procs)
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/site-packages/tensorpack/utils/concurrency.py", line 244, in start_proc_mask_signal
    p.start()
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/david/miniconda3/envs/frcnn/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'TrainingDataPreprocessor.__init__.<locals>.<lambda>'

```

One workaround:
```python
def data_pass_through(data):
    return data
...
def __init__(self, cfg):
    self.cfg = cfg
    self.aug = imgaug.AugmentorList(
        [
            CustomResize(cfg.PREPROC.TRAIN_SHORT_EDGE_SIZE, cfg.PREPROC.MAX_SIZE),
            imgaug.Flip(horiz=True),
            imgaug.MapImage(aug_fxn, data_pass_through),
        ]
    )
```

I am modifying the example, but I figured this use case might be relevant enough to others that it warranted attention.

Thanks!

**Comment by ppwwyyxx** [comment] 2019-05-17 23:13
The reason to use "spawn" is that it is safer and have lower memory usage. But "spawn" does not support lambda functions (this is a Python limitation) and this is exactly why I moved the preprocessor from a lambda to a class.
If you want to use lambda, remove the "spawn" method from `train.py`.

**Comment by ppwwyyxx** [comment] 2019-05-18 14:48
Closing as this is by design. You can avoid this by not using the spawn method.

**Closed by ppwwyyxx** 2019-05-18 14:48 UTC
