### ISSUE TITLE
[DQN] Issues restoring saved model

### ISSUE THREAD

**Issue by JamesBrightman** [tensorpack/tensorpack#1094] opened 2019-02-22 12:01 UTC
### 1. What you did:

I'm training a model using the DQN implementation. I run it for 2 epochs (global sep 50,000) and stop the training. I now want to resume this training so I run; 
`
!python ./DQN-Run.py --env BreakoutDeterministic-v4 --algo DQN  --load ./train_log/DQN-BreakoutDeterministic-v4/model-50000 
`
to load my model.

However when the model is loaded, the **epsilon/exploration** is reset to 1.0. At 50k steps epsilon should have decayed but when it's restored it goes back to 1. This makes continuing training extremely difficult. Epoch is also overwritten.  This is the message I get;

[0222 00:41:56 @steps.py:124] Start training with global_step=50000
[0222 00:41:59 @graph.py:73] Running Op RunOp_1/update_target_network ...
[0222 00:41:59 @expreplay.py:181] Populating replay memory with epsilon=1.0 ...
100% 5000/5000 [00:05<00:00, 923.77it/s]
[0222 00:42:05 @param.py:158] [HyperParamSetter] At global_step=50000, exploration is set to 1.000000
[0222 00:42:05 @monitor.py:352] WRN History epoch=2 from JSON is not the predecessor of the current starting_epoch=1
[0222 00:42:05 @monitor.py:353] WRN If you want to resume old training, either use `AutoResumeTrainConfig` or correctly set the new starting_epoch yourself to avoid inconsistency. 

I have trained this up to 28 epochs before I had to stop it. When trying to load it back in, the same issue occurred and I went from scores of avg ~100 points on breakout back down to ~1.

I don't have this issue with the A3C loading process, that seems to pick up where it left off.

Please let me know if there is something I can do to solve this issue. Thanks.

**Comment by ppwwyyxx** [comment] 2019-02-22 17:21
`exploration` and `epoch` are reset because they are not tensorflow variables, and therefore cannot be saved in a tensorflow checkpoint.

Same thing in A3C: epoch will be reset.

You can start the training by providing a `starting_epoch`, as mentioned in the above logs. (See https://tensorpack.readthedocs.io/modules/train.html#tensorpack.train.TrainConfig).

You'll also need to modify `init_exploration=1.0` to a different initial exploration you need.

**Comment by ppwwyyxx** [comment] 2019-03-01 21:51
Closing and feel free to reopen if the problem is not solved.

**Closed by ppwwyyxx** 2019-03-01 21:51 UTC
Labels: examples
