### ISSUE TITLE
Quantized model bitwidth still Float32

### ISSUE THREAD

**Issue by Abhishek2271** [tensorpack/tensorpack#1529] opened 2021-06-28 22:40 UTC
### 1. What you did:

(1) I trained a 1,2,4 DoReFa net on a desktop PC  on SVHN dataset

(2) Without any changes to the code

(3) At the end of the training, checkpoints were generated. I used the latest checkpoint to view the saved weights

### 2. What you observed:

(1) The weights and biases were still in tf.float32 format 

I am very sorry for a very simple question, I am new to quantization andI thought that the model generated would be in 1,2, 4 format.
In the readme, it is mentioned that the computations are still done in tf.float32. But I do not quite understand what this means.  I wanted to run inference on quantized model to study its adversarial accuracy. Is there any way to get a quantized version of the model?

**Comment by ppwwyyxx** [comment] 2021-06-29 00:07
Duplicate of #573

**Closed by ppwwyyxx** 2021-06-29 00:07 UTC

**Comment by Abhishek2271** [comment] 2021-06-29 10:13
Thank you very much for the prompt response. I am trying to use DoReFa for quantization for my research project and the closed issues contain a ton of information.
Thanks again for your prompt response.

**Comment by Abhishek2271** [comment] 2021-06-29 20:16
Hi @ppwwyyxx,

I am sorry I write again. As per the suggestions in the old tickets, I loaded the checkpoint for post-processing. I can see quantized variables now. But I get the below error while saving the checkpoint. Creating the dictionary of updated variables, however, does not give any error and provided quantized variables as output.


![error_dorefa](https://user-images.githubusercontent.com/33551684/123861550-9a438400-d927-11eb-98ce-f8fabeea7f3b.png)

The code snippet I used is:


BITW = 1
BITA = 2
BITG = 4

def getBinarizedWights():

    fw, fa, fg = get_dorefa(BITW, BITA, BITG)

    dict = {}
    def get_weights():           
        if not name.endswith('W') or 'conv0' in name or 'fc' in name:
            return reader[name]
        else:
            return fw(reader[name])

    reader = tfutils.varmanip.load_checkpoint_vars(r'C:\Users\sab\Downloads\AI Testing\Source\Dorefanet\tensorpack\examples\DoReFa-Net\train_log\svhn-dorefa-1,2,4\model-4721')
    for name in reader:
        val = get_weights()
        if(not "/Adam" in name and not "bn" in name):
            #print(keys, ":", val, "\n")
            dict[name] = val
    return dict

dict = getBinarizedWights()
tfutils.varmanip.save_checkpoint_vars(dict, r"C:\Users\sab\Downloads\AI Testing\Source\Dorefanet\tensorpack\examples\DoReFa-Net\train_log\svhn-dorefa-1,2,4\model-55")

**Comment by ppwwyyxx** [comment] 2021-06-29 20:47
`save_checkpoint_vars` requires the values to be numpy arrays

**Comment by Abhishek2271** [comment] 2021-06-29 20:55
This made it work. Thank you, I really appreciate it.

**Comment by Abhishek2271** [comment] 2021-07-05 00:00
Hi @ppwwyyxx,

After going through the paper again and the discussions on #573, #851, #27, and #30, it makes sense that the current model is float32. But just to confirm my understanding:  
1. The current network is trained with float32 precision (as stated in the readme as well) but the quantized weights can be obtained after post-processing. However, if we are using the dorefa alexnet or svhn net, for inference it is not necessary to post-process because these models already apply fw().  

2. The network is still quantized although it is at float32. For instance, for binarized weights, there will be two possible float32 values. These can of course later be scaled to -1 and 1. Similarly, 2-bit quantization will produce 2-bit quantized float32 values.  

Scaling is beneficial when we run the network on specific hardware where integer representation will cause the convolution operations to be bitwise rather than float32 operations since this will increase the training and inference speed. But since I am only researching the impact of quantization on inference and I do so on my desktop, is it necessary to scale these values? From my understanding, the current network, although slow, is still quantized.  

Further, if I use the saved model and use it for inference by loading the weight values somewhere else, will activations be still quantized? It seems like the activation will not be quantized in this case.
