### ISSUE TITLE
W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed

### ISSUE THREAD

**Issue by XuanBaby** [tensorpack/tensorpack#1373] opened 2019-12-19 06:28 UTC
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:

(1) **If you're using examples, what's the command you run:**
`python3 train.py`

(2) **If you're using examples, have you made any changes to the examples? Paste `git status; git diff` here:**

(3) **If not using examples, help us reproduce your issue:**

  It's always better to copy-paste what you did than to describe them.

  Please try to provide enough information to let others __reproduce__ your issues.
  Without reproducing the issue, we may not be able to investigate it.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**

It's always better to copy-paste what you observed instead of describing them.

It's always better to paste **as much as possible**, although sometimes a partial log is OK.

Tensorpack typically saves stdout to its training log.
If stderr is relevant, you can run a command with `my_command 2>&1 | tee logs.txt`
to save both stdout and stderr to one file.
`W tensorflow/core/kernels/queue_base.cc:277] _0_QueueInput/input_queue: Skipping cancelled enqueue attempt with queue not closed Traceback (most recent call last): File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call return fn(*args) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn options, feed_dict, fetch_list, target_list, run_metadata) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun run_metadata) tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found. (0) Invalid argument: Input to reshape is a tensor with 600 values, but the requested shape has 120000 [[{{node gradients/rpn_1/Reshape_grad/Reshape}}]] (1) Invalid argument: Input to reshape is a tensor with 600 values, but the requested shape has 120000 [[{{node gradients/rpn_1/Reshape_grad/Reshape}}]] [[gradients/AddN_154/_4309]] 0 successful operations. 0 derived errors ignored.
During handling of the above exception, another exception occurred: Traceback (most recent call last): File "train.py", line 130, in <module> launch_train_with_config(traincfg, trainer) File "../../tensorpack/train/interface.py", line 101, in launch_train_with_config extra_callbacks=config.extra_callbacks) File "../../tensorpack/train/base.py", line 342, in train_with_defaults steps_per_epoch, starting_epoch, max_epoch) File "../../tensorpack/train/base.py", line 314, in train self.main_loop(steps_per_epoch, starting_epoch, max_epoch) File "../../tensorpack/utils/argtools.py", line 168, in wrapper return func(*args, **kwargs) File "../../tensorpack/train/base.py", line 279, in main_loop self.run_step() # implemented by subclass File "../../tensorpack/train/base.py", line 179, in run_step self.hooked_sess.run(self.train_op) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 754, in run run_metadata=run_metadata) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1252, in run run_metadata=run_metadata) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1353, in run raise six.reraise(*original_exc_info) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/six.py", line 693, in reraise raise value File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1338, in run return self._sess.run(*args, **kwargs) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1411, in run run_metadata=run_metadata) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 1169, in run return self._sess.run(*args, **kwargs) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 950, in run run_metadata_ptr) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1173, in _run feed_dict_tensor, options, run_metadata) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1350, in _do_run run_metadata) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1370, in _do_call raise type(e)(node_def, op, message) tensorflow.python.framework.errors_impl.InvalidArgumentError: 2 root error(s) found.
Original stack trace for 'gradients/rpn_1/Reshape_grad/Reshape': File "train.py", line 130, in <module> launch_train_with_config(traincfg, trainer) File "../../tensorpack/train/interface.py", line 91, in launch_train_with_config model.build_graph, model.get_optimizer) File "../../tensorpack/utils/argtools.py", line 168, in wrapper return func(*args, **kwargs) File "../../tensorpack/train/tower.py", line 224, in setup_graph train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn) File "../../tensorpack/train/trainers.py", line 447, in _setup_graph grads = self._make_get_grad_fn(input, get_cost_fn, get_opt_fn)() File "../../tensorpack/train/tower.py", line 281, in get_grad_fn return compute_grad_from_inputs(*inputs) File "../../tensorpack/train/tower.py", line 276, in compute_grad_from_inputs aggregation_method=self.AGGREGATION_METHOD) File "../../tensorpack/tfutils/optimizer.py", line 29, in compute_gradients return self._opt.compute_gradients(*args, **kwargs) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 512, in compute_gradients colocate_gradients_with_ops=colocate_gradients_with_ops) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 158, in gradients unconnected_gradients) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 731, in _GradientsHelper lambda: grad_fn(op, *out_grads)) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 403, in _MaybeCompile return grad_fn() # Exit early File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/ops/gradients_util.py", line 731, in <lambda> lambda: grad_fn(op, *out_grads)) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/ops/array_grad.py", line 540, in _ReshapeGrad return [array_ops.reshape(grad, array_ops.shape(op.inputs[0])), None] File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 7715, in reshape "Reshape", tensor=tensor, shape=shape, name=name) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 788, in _apply_op_helper op_def=op_def) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func return func(*args, **kwargs) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3616, in create_op op_def=op_def) File "/public/home/yangxuan1/Build/python-3.6.8/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2005, in __init__ self._traceback = tf_stack.extract_stack()`
(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.

### 3. What you expected, if not obvious.

If you expect higher speed, please read
http://tensorpack.readthedocs.io/tutorial/performance-tuning.html
before posting.

If you expect the model to work better, only in one of the two conditions can we help with it:
(1) You're unable to reproduce the results documented in tensorpack examples.
(2) It appears to be a tensorpack bug.

Otherwise, how to train a good model on your task or your
modifications is a machine learning question.
We do not answer machine learning questions and it is your responsibility to
figure out how to make your models more accurate.

### 4. Your environment:

Paste the output of this command: `python -c 'import tensorpack.tfutils as u; print(u.collect_env_info())'`
If this command failed, tell us your version of Python/TF/tensorpack.
-------------------  -----------------------------------------------------------------------------
sys.platform         linux
Python               3.6.8 (default, Aug  5 2019, 16:08:54) [GCC 7.2.1 20170829 (Red Hat 7.2.1-1)]
Tensorpack           0.9.8
Numpy                1.16.4
TensorFlow           1.14.0/v1.14.0-1102-ga102540
TF Compiler Version  7.3.1 20180303 (Red Hat 7.3.1-5)
TF CUDA support      False
TF MKL support       False
TF XLA support       False
Free RAM             110.42/125.65 GB
CPU Count            32
Horovod              0.18.1
cv2                  4.1.2
msgpack              0.6.2
python-prctl         True
-------------------  -----------------------------------------------------------------------------

You may often want to provide extra information related to your issue, but
at the minimum please try to provide the above information __accurately__ to save effort in the investigation.

**Comment by ppwwyyxx** [comment] 2019-12-19 06:51
Please answer the questions in the issue template and post full logs.

**Comment by XuanBaby** [comment] 2019-12-19 07:02
@ppwwyyxx  ok I run the example FasterRCNN ,and the log is 
[xuan-data-worker_0.log](https://github.com/tensorpack/tensorpack/files/3982107/xuan-data-worker_0.log)

**Comment by ppwwyyxx** [comment] 2019-12-19 07:20
Please also answer: 

> (2) If you're using examples, have you made any changes to the examples?

If you have not changed the model code, then this reads like a tensorflow bug to me. However I cannot proceed with debugging unless there are instructions for me to reproduce it on a common dataset.

**Comment by XuanBaby** [comment] 2019-12-20 01:16
@ppwwyyxx  I am not change the model code  and  the complete log file is 
[xuan.log](https://github.com/tensorpack/tensorpack/files/3986243/xuan.log)

**Comment by XuanBaby** [comment] 2019-12-20 06:17
@ppwwyyxx  Hi~ Could you give me some advice about this error?  or How should I debug the program?

**Comment by ppwwyyxx** [comment] 2019-12-20 07:27
Since the crash is likely to be a tensorflow bug, I would upgrade tensorflow first.

From the second log you provided, the model diverges (has nan loss) in the end. Such behavior does sometimes trigger a tensorflow crash (e.g. a bug fixed in https://github.com/tensorflow/tensorflow/commit/1c94a5bed5402c4f764ec9b6b25d00af529c541b). 
However I don't expect that a normal training on COCO will diverge. 

I can try to reproduce but I'll need to know what changes you've made as requested in the issue template. For example, you've changed `MODE_MASK` to False according to the log but you have not mentioned it so far.

**Comment by XuanBaby** [comment] 2019-12-20 08:36
@ppwwyyxx  Thank you for your reply.the git diff file is 
[diff-log.txt](https://github.com/tensorpack/tensorpack/files/3987423/diff-log.txt)

**Comment by ppwwyyxx** [comment] 2019-12-20 09:21
```diff
diff --git a/examples/FasterRCNN/data.py b/examples/FasterRCNN/data.py
index ea23e0f..f0eba55 100644
--- a/examples/FasterRCNN/data.py
+++ b/examples/FasterRCNN/data.py
@@ -48,8 +48,6 @@ def print_class_histogram(roidbs):
         # filter crowd?
         gt_inds = np.where((entry["class"] > 0) & (entry["is_crowd"] == 0))[0]
         gt_classes = entry["class"][gt_inds]
-        if len(gt_classes):
-            assert gt_classes.max() <= len(class_names) - 1
         gt_hist += np.histogram(gt_classes, bins=hist_bins)[0]
     data = list(itertools.chain(*[[class_names[i + 1], v] for i, v in enumerate(gt_hist[1:])]))
     COL = min(6, len(data))
@@ -99,8 +97,6 @@ class TrainingDataPreprocessor:
         points = tfms.apply_coords(points)
         boxes = point8_to_box(points)
         if len(boxes):
-            assert klass.max() <= self.cfg.DATA.NUM_CATEGORY, \
-                "Invalid category {}!".format(klass.max())
             assert np.min(np_area(boxes)) > 0, "Some boxes have zero area!"
 
         ret = {"image": im}
```
I'm not sure why they would be removed. Invalid classes will likely lead to NaNs in training.
Other part of the diff looks reasonable. The diff is however not based on tensorpack's commits, but on some of your private commits. So I can only assume your previous commits are also reasonable.

Following the diff I run a 4-GPU training with zero changes to tensorpack's current master, with `--config TRAINER=horovod DATA.BASEDIR=~/data/coco MODE_MASK=False`. It finished 94 epochs without any errors or NaNs. My environment is
```
sys.platform          linux
Python                3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]
Tensorpack            0.9.8
Numpy                 1.16.4
TensorFlow            1.15.0-rc2/v1.15.0-rc2-0-g5adb433d78
TF Compiler Version   7.4.0
TF CUDA support       True
TF MKL support        True
TF XLA support        False
Nvidia Driver         /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.410.79
CUDA                  /cuda/10.0/lib64/libcudart.so.10.0.130
CUDNN                 /cudnn-7.6.4-cuda10/lib64/libcudnn.so.7.6.4
NCCL                  /nccl_2.4.7-1_cuda10.0/lib/libnccl.so.2.4.7
CUDA_VISIBLE_DEVICES  0,1,2,3
GPU 0,1,2,3           Tesla V100-SXM2-16GB
Free RAM              464.05/503.79 GB
CPU Count             80
Horovod               0.18.2
cv2                   3.4.1
msgpack               0.6.2
python-prctl          False
```

Since I cannot reproduce the issue with the given instructions I'll close the issue.

**Closed** 2020-02-21 07:18 UTC

**Comment by Adblu** [comment] 2020-07-06 15:07
@XuanBaby Have you fixed the problem ? I have exactly the same problem now

**Comment by Adblu** [comment] 2020-07-07 09:40
For me, it turned out, that 3 images had annotations very close to the edge,and after augmentation, they were moved further away then the max size of the image, therefore the area of the polygon, were 0. Make sure the annotations size != 0.
