### ISSUE TITLE
Why the pre-trained .npz files contain only float32 weights in the DoReFa-net?

### ISSUE THREAD

**Issue by asjmasjm** [tensorpack/tensorpack#851] opened 2018-08-03 03:14 UTC
Hi

I download the pre-trained model of the DoReFa-AlexNet to test the efficiency of the low-bitwidth net. Why the trained models (eg. 1, 2, 6 or 8, 8, 8) contain only the float32 weights in each convolution layer instead of quantized k-bit-number ones? And if so, I am wondering whether the convolution calculations in the forward propagation are float32-based?

**Comment by ppwwyyxx** [comment] 2018-08-03 03:29
1. Duplicate of #573 
2. Answered in the readme already: https://github.com/tensorpack/tensorpack/tree/master/examples/DoReFa-Net#speed

**Closed by ppwwyyxx** 2018-08-03 03:29 UTC

**Comment by asjmasjm** [comment] 2018-08-03 04:52
Thank you for your reply. However, two things are still not very clear for me:

1. Suppose I have realized all the necessary quantized operations in the forwarded propagation, does it mean the downloaded pre-trained 1-2-6 or 8-8-8 model is testable after I manually quantized every weight elements using fw() as you have suggested in #573?

2. By claiming "In this implementation, quantized operations are all performed through tf.float32", my understanding is that all the data format is still float32 in the python scripts you provide. For example: 
"
......
.Conv2D('conv0', 96, 12, strides=4, padding='VALID', use_bias=True)
.apply(activate)
.Conv2D('conv1', 256, 5, padding='SAME', split=2)
......
"
Although the quantized activate function are applied, the conv1 still perform float32-based convolution calculations in your open implementation. And the npz model is also trained under this environment which explains the float32 weights it contains. 
I do not know if it is correct.

**Comment by ppwwyyxx** [comment] 2018-08-03 05:40
1. Yes
2. 
> Although the quantized activate function are applied, the conv1 still perform float32-based convolution calculations in your open implementation.

Yes

> And the npz model is also trained under this environment which explains the float32 weights it contains.

Using float32 weights for training is by design of the listed quantization methods. It is not about this specific implementation.

**Comment by asjmasjm** [comment] 2018-08-03 06:30
Yes I kind of misunderstood the quantization mechanism until I walked through the discussions in #27. I now know the weights should still be float32 after quantization whatsoever while most of the multiplications and additions in Cov and FC layers are bitwisely operated according to the equation (3) of your paper. 

Another thought: I think it is no need of quantization if I use the provided dorefa-alexnet.py with the pre-trained npz model to test as the quantization layers are already provided between Conv layers in this script. And the accuracy should be almost the same but the speed is slower because the Conv2d in it are float32-based. I do not know if it is correct as I am to test the float32 version net anyway.
