### ISSUE TITLE
Increasing the batch size in faster rcnn training.

### ISSUE THREAD

**Issue by dvlshah** [tensorpack/tensorpack#1346] opened 2019-10-16 08:37 UTC
How to increase batch size for faster rcnn training? I am not able find the batch size parameter in the config.py or anywhere else.

**Comment by ppwwyyxx** [comment] 2019-10-16 08:47
answered in https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/NOTES.md
and a duplicate of #1344

**Closed by ppwwyyxx** 2019-10-16 08:47 UTC
