### ISSUE TITLE
RUN FasterRCNN+FPN with tensorflow 1.4 or 1.5 

### ISSUE THREAD

**Issue by LandyGuo** [tensorpack/tensorpack#841] opened 2018-07-24 16:19 UTC
I am running FasterRCNN with FPN examples with tf1.4, for some reason, it's not possible for me to update tensorflow, I try to walk around this issue: https://github.com/tensorflow/tensorflow/issues/14657  with your origin implementation like

>        
       def ff_true():
            roi_feature_fastrcnn = multilevel_roi_align(p23456[:4], rcnn_boxes, 7)#  Nxcx7*7
            fastrcnn_head_func = getattr(model_frcnn, cfg.FPN.FRCNN_HEAD_FUNC)
            fastrcnn_label_logits, fastrcnn_box_logits = fastrcnn_head_func(
                      'fastrcnn', roi_feature_fastrcnn, cfg.DATA.NUM_CLASS)
            return roi_feature_fastrcnn, fastrcnn_label_logits, fastrcnn_box_logits
        def ff_false():
            ncls = cfg.DATA.NUM_CLASS
            return tf.zeros([0, 2048, 7, 7]), tf.zeros([0, ncls]), tf.zeros([0, ncls - 1, 4])
        
        roi_feature_fastrcnn, fastrcnn_label_logits, fastrcnn_box_logits = tf.cond(
                                         tf.size(rcnn_boxes) > 0, ff_true, ff_false)

which replaces the counterpart code
https://github.com/tensorpack/tensorpack/blob/master/examples/FasterRCNN/train.py#L332-L336 ,  but still happens:

> could not convert BatchDescriptor {count: 0 feature_map_count: 256 spatial: 14 14  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX} to cudnn tensor descriptor: CUDNN_STATUS_BAD_PARAM

could you  please help figure out what else should I do?

**Comment by ppwwyyxx** [comment] 2018-07-24 16:36
Duplicate of #828

**Closed** 2018-07-24 16:41 UTC
