### ISSUE TITLE
TensorPack results on ResNet50, ResNet101, and ResNet152 for DoReFa-Net

### ISSUE THREAD

**Issue by snownus** [tensorpack/tensorpack#948] opened 2018-10-25 05:21 UTC
Can release results of TensorPack results on ResNet50, ResNet101, and ResNet152?

**Comment by ppwwyyxx** [comment] 2018-10-25 05:40
It's in the examples.

**Comment by ppwwyyxx** [comment] 2018-10-25 09:48
We have not trained such models.

**Comment by ppwwyyxx** [comment] 2018-10-25 20:30
Duplicate of #470 .

**Closed by ppwwyyxx** 2018-10-25 20:30 UTC
Labels: examples
