### ISSUE TITLE
Fastercnn NHWC format support

### ISSUE THREAD

**Issue by mhtarora39** [tensorpack/tensorpack#1504] opened 2021-01-15 14:51 UTC
Hi I have trained Faster Rcnn model on GPU with tensorflow 1.14 but i want to deploy that model on CPU. I am getting consistent error.

tensorflow.python.framework.errors_impl.InvalidArgumentError: Default MaxPoolingOp only supports NHWC on device type CPU
         [[Node: pool0/MaxPool = MaxPool[T=DT_FLOAT, data_format="NCHW", ksize=[1, 1, 3, 3], padding="VALID", strides=[1, 1, 2, 2], _device="/job:loca
lhost/replica:0/task:0/device:CPU:0"](Pad_1)]]

Can you please guide me what changes i need to do to work this trained network of CPU ? I  have saved model with weight in serve mode. 

I have tried with mkl enabled tensorflow 1.19 still no luck.That crashed with.

tensorflow.python.framework.errors_impl.AbortedError: Operation received an exception:Status: 3, message: could not initialize a memory descriptor, in
 file tensorflow/core/kernels/mkl_concat_op.cc:813
         [[Node: multilevel_roi_align_1/concat = _MklConcatV2[N=4, T=DT_FLOAT, Tidx=DT_INT32, _kernel="MklOp", _device="/job:localhost/replica:0/task:
0/device:CPU:0"](multilevel_roi_align_1/roi_level2/roi_align/AvgPool, multilevel_roi_align_1/roi_level3/roi_align/AvgPool, multilevel_roi_align_1/roi_
level4/roi_align/AvgPool, multilevel_roi_align_1/roi_level5/roi_align/AvgPool, multilevel_roi_align_1/fpn_map_rois_to_levels/GatherV2/axis, multilevel
_roi_align_1/roi_level2/roi_align/AvgPool:1, multilevel_roi_align_1/roi_level3/roi_align/AvgPool:1, multilevel_roi_align_1/roi_level4/roi_align/AvgPoo
l:1, multilevel_roi_align_1/roi_level5/roi_align/AvgPool:1, DMT/_461)]]

 I am new to tensorflow please guide me !

**Comment by ppwwyyxx** [comment] 2021-01-25 10:15
Duplicate of #1024

**Closed by ppwwyyxx** 2021-01-25 10:15 UTC
