### ISSUE TITLE
ValueError: Op type not registered 'NcclAllReduce' in binary running on 621b71bd67b1

### ISSUE THREAD

**Issue by adoudou2008** [tensorpack/tensorpack#913] opened 2018-09-27 01:22 UTC
System information：
OS Platform and Distribution : Linux Ubuntu 16.04
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
TensorFlow installed from (source or binary): Binary
TensorFlow version (use command below): v1.10.0-0-g656e7a2b34 1.10.0
Python version: 3.6
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: CUDA 9.0  cuDNN 7.1.
GPU model and memory: GTX1080Ti 11GB * 4.
Exact command to reproduce: gen_nccl_ops.nccl_all_reduce( ... )

Hi, I'm trying to implement multi-gpu tensorflow code.
I am trying to use gen_nccl_ops.nccl_all_reduce to sum values from each GPU, however, the code raises ValueError written below.

ValueError: Op type not registered 'NcclAllReduce' in binary running on 621b71bd67b1. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.)tf.contrib.resamplershould be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. while building NodeDef 'Tower_0/Network/NcclAllReduce'

Source code：
This is my part code of definition of BN layer:

 batch_mean = gen_nccl_ops.nccl_all_reduce(
            input=batch_mean,
            reduction='sum',
            num_devices=self.num_devices,
            shared_name=shared_name + '_NCCL_mean') * (1.0 / self.num_devices)
 batch_mean_square = gen_nccl_ops.nccl_all_reduce(
            input=batch_mean_square,
            reduction='sum',
            num_devices=self.num_devices,
            shared_name=shared_name + '_NCCL_mean_square') * (1.0 / self.num_devices)

**Comment by ppwwyyxx** [comment] 2018-09-27 01:30
This issue seems unrelated to tensorpack because it sounds like an issue running your own code.

**Comment by adoudou2008** [comment] 2018-09-27 01:34
I am referring to the source code of tensorpack, wrote some code, may have some errors about NCCL, I hope someone can answer.

**Comment by ppwwyyxx** [comment] 2018-09-27 01:39
Confirmed that this is not a tensorpack issue. Closing now.
We are sorry for your problems but this is not the place for tensorflow questions.

**Closed by ppwwyyxx** 2018-09-27 01:39 UTC

**Comment by adoudou2008** [comment] 2018-09-27 01:40
sorry。my fault。
