### ISSUE TITLE
Tensorpack dataflow with PrefetchdataZMQ memory consumption

### ISSUE THREAD

**Issue by DeeperDeeper** [tensorpack/tensorpack#1293] opened 2019-08-01 17:38 UTC
If you're asking about an unexpected problem which you do not know the root cause,
use this template. __PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

If you already know the root cause to your problem,
feel free to delete everything in this template.

### 1. What you did:
I am training a CNN model using Tensorpack training interface.
here the function that I used:
  ```
 def get_dataflow(self, is_train):
        """
        This function initializes the tensorpack dataflow and serves generator
        for training operation.
        Parameters
        ----------
        is_train : bool
            training or inference
        Returns
        -------
        dataflow object
        """
        df = PascalDataFlow(input_size=(self.input_height, self.input_width),
                            pascal_data=self.pascal_data_path, select_ids=self.select_ids)
        df.prepare()
        df = MapData(df, self.read_img)
        if is_train:
            df = MapData(df, self.augment)
        else:
            df = MapData(df, self.augment_valid)
        df = MapData(df, self.build_sample)
        df = PrefetchDataZMQ(df, nr_proc=8)
        return df

    def batch_dataflow(self, df, batch_size):
        """
        The function builds batch dataflow from the input dataflow of samples
        Parameters
        ----------
        df : Dataflow object
            dataflow of samples
        batch_size : Integer
         batch size

        Returns
        -------
        dataflow of batches

        """
        df = BatchData(df, batch_size, use_list=False)
        df = MapData(df, lambda x: (
            [x[0]], [x[1], x[2], x[3]]
        )
                     )
        df.reset_state()
        return df
```
during the training:
```
df_tr = data_set_tr.get_dataflow(is_train=True)
batch_df_tr = data_set_tr.batch_dataflow(df_tr, batch_size)
train_gen = gen(batch_df_tr)
....
model.fit_generator(train_generator,....
```
batch_size = 2
image_size =(512, 512, 3)
GPU:  GTX 1080

### 2. What you observed:

(1) **Include the ENTIRE logs here:**

WRN Starting a process with 'fork' method is not safe and may consume unnecessary extra memory

(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.
![Screenshot from 2019-08-01 13-34-41](https://user-images.githubusercontent.com/13174842/62314549-4d1bb680-b461-11e9-82e8-b4f467bc231f.png)

### 3. What you expected, if not obvious.

The memory consumption is too high!!! Why 14GB. My dataset is about 2 GB

### 4. Your environment:

Paste the output of this command: `python -c 'import tensorpack.tfutils as u; print(u.collect_env_info())'`
sys.platform          linux
Python                3.7.3 (default, Mar 27 2019, 22:11:17) [GCC 7.3.0]
Tensorpack            v0.9.5-0-g372356f
Numpy                 1.15.4
TensorFlow            1.14.0/unknown
TF Compiler Version   5.4.0
TF CUDA support       True
TF MKL support        False
TF XLA support        False
Nvidia Driver         /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.396.54
CUDA                  /usr/local/cuda/lib64/libcudart.so.9.0.176
CUDNN                 /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0
NCCL
CUDA_VISIBLE_DEVICES  None
GPU 0                 GeForce GTX 1080 with Max-Q Design
Free RAM              0.80/15.59 GB
CPU Count             12
cv2                   4.1.0
msgpack               0.6.1
python-prctl          True

**Comment by DeeperDeeper** [comment] 2019-08-01 18:02
I change `n_proc=1` and get `8 G` of consumption but I think still too high!!

**Comment by ppwwyyxx** [comment] 2019-08-01 18:08
This depends on how you implement your dataflow. If you read everything to memory then it's certainly going to be high.
You can see what the memory use is by just disabling `PrefetchDataZMQ`.

**Comment by DeeperDeeper** [comment] 2019-08-01 18:29
By disabling `PrefetchDataZMQ` I got 7 GB!! so this is not the problem
I don't read anything on the memory. I read the content of the image in the `get_dataflow()` function

**Comment by ppwwyyxx** [comment] 2019-08-01 18:32
Then may be it's not related to tensorpack at all. Without more information I cannot tell why would you use 7G of memory.

**Comment by DeeperDeeper** [comment] 2019-08-01 19:26
Thanks. I am reading about and I think the problem is coming from keras fit_generator which accumulate memory!!!??

**Comment by ppwwyyxx** [comment] 2019-08-01 19:30
The best way to disentangle dataflow from other libraries is to use [TestDataSpeed](https://tensorpack.readthedocs.io/modules/dataflow.html#tensorpack.dataflow.TestDataSpeed) to run the dataflow alone for a while.

**Comment by DeeperDeeper** [comment] 2019-08-01 19:56
I can confirm that the problem is coming from TensorPack. I run:
   ```
    df = dataset.get_dataflow(True)
    df = PrefetchDataZMQ(df, nr_proc=1)
    df = BatchData(df, batch_size, use_list=False)
    TestDataSpeed(df, size=2000).start()
```
The memory strat from ~=3G and start accumulated till 5G after 22% !!! I thin the problem is coming from this warning 
 **WRN Starting a process with 'fork' method is not safe and may consume unnecessary extra memory. Use 'forkserver' method (available after Py3.4) instead if you run into any issues**

**Comment by ppwwyyxx** [comment] 2019-08-01 19:59
Could you disable PrefetchDataZMQ to see whether the memory comes from your own dataflow?

**Comment by DeeperDeeper** [comment] 2019-08-02 13:06
Thanks. I release some references and now it is much better. However, it is still increasing while it is training! It is a generator, so, normally the memory use should be constant!

**Comment by ppwwyyxx** [comment] 2019-08-02 17:01
I'm not sure whether you're assuming the issue is still related to tensorpack. If you think so, it's better to show runnable code that demonstrates such issues.

**Comment by DeeperDeeper** [comment] 2019-08-03 20:34
I am still running my code and still having problem with data accumulation. Today, I get this exception
`tensorpack.dataflow.base.DataFlow Terminated`.
 I am using 2000 samples, 200 epochs and this exception is raised at 142 epochs

**Comment by ppwwyyxx** [comment] 2019-08-03 22:49
This message supposed to only appear when you kill your dataflow or there are bugs in your dataflow.
Again, if you think it's a tensorpack issue, please show runnable code that demonstrates such issues.

**Comment by ppwwyyxx** [comment] 2019-08-22 17:23
There seems to be no signal indicating a tensorpack issue, so closing. Feel free to reopen if you can isolate and identify an issue of tensorpack.

**Closed by ppwwyyxx** 2019-08-22 17:23 UTC
